-- เพิ่ม Workflow ทวนสอบ/ตรวจสอบ/อนุมัติ สำหรับ Prototype
create table if not exists public.flow_reviews (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text not null,
  status text not null check (status in ('verified','checked','approved')),
  operator_name text,
  assistant_name text,
  head_name text,
  note text
);

alter table public.flow_reviews enable row level security;

drop policy if exists "dashboard_read_reviews" on public.flow_reviews;
create policy "dashboard_read_reviews" on public.flow_reviews
for select to anon using (true);

drop policy if exists "dashboard_insert_reviews" on public.flow_reviews;
create policy "dashboard_insert_reviews" on public.flow_reviews
for insert to anon with check (true);

grant usage on schema public to anon;
grant select, insert on table public.flow_reviews to anon;
grant usage, select on sequence public.flow_reviews_id_seq to anon;

-- หมายเหตุ Prototype:
-- flow_readings คือข้อมูลดิบจาก ESP32
-- Dashboard จะสรุปเป็น "บันทึก Flow รายชั่วโมง" อัตโนมัติ
-- ก่อนใช้งานจริงควรเปลี่ยนจาก anon write เป็น authentication/role-based access
