-- Run in Supabase SQL Editor

create table if not exists public.flow_readings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text not null,
  flow_m3h double precision not null,
  input_voltage double precision
);

create index if not exists flow_readings_created_at_idx
on public.flow_readings (created_at desc);

alter table public.flow_readings enable row level security;

-- Prototype policies. Tighten authentication before production use.
create policy "prototype can insert readings"
on public.flow_readings for insert
to anon
with check (true);

create policy "prototype can read readings"
on public.flow_readings for select
to anon
using (true);
